//! The type registry: type references, and a name-keyed catalog of parsers.
//!
//! [`TypeRef`] is how a port or workflow input names a domain type —
//! `"GitHubRepo"` or `"list<GitHubRepo>"` — the string form that appears in
//! the DSL and in JSON schemas. [`TypeRegistry`] is the runtime catalog that
//! resolves a [`TypeName`] to its [`TypeInfo`] and its parser, built once by
//! the [`domain_types`] macro from the same list that builds
//! [`crate::type_infos`], so the two cannot drift.

use std::borrow::Cow;
use std::collections::HashMap;
use std::fmt;
use std::sync::{Arc, LazyLock};

use crate::object::DomainObject;
use crate::{DomainType, ParseError, TypeInfo};

/// The pattern every [`TypeName`] must match: an uppercase ASCII letter,
/// then any number of ASCII letters or digits.
const TYPE_NAME_PATTERN: &str = "^[A-Z][A-Za-z0-9]*$";

static TYPE_NAME_REGEX: LazyLock<regex::Regex> =
    LazyLock::new(|| regex::Regex::new(TYPE_NAME_PATTERN).expect("TYPE_NAME_PATTERN is valid"));

/// The name of a domain type, as it appears in [`TypeRef`], port
/// declarations, and JSON schemas: `PascalCase`, no separators.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct TypeName(String);

impl TypeName {
    /// Parse a type name, checking it against [`TYPE_NAME_PATTERN`].
    ///
    /// # Errors
    ///
    /// Returns [`ParseError`] when `input` does not match the pattern.
    pub fn parse(input: &str) -> Result<Self, ParseError> {
        if TYPE_NAME_REGEX.is_match(input) {
            Ok(Self(input.to_string()))
        } else {
            Err(ParseError::new(
                "TypeName",
                format!(
                    "{} is not a valid type name (expected to match `{TYPE_NAME_PATTERN}`)",
                    crate::quoted(input)
                ),
            ))
        }
    }

    /// Borrow the name as a plain string.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Build a [`TypeName`] from a `&'static str` known to already match the
    /// pattern, such as a [`DomainType::TYPE_NAME`]. Debug-asserts the
    /// pattern rather than returning `Result`, because a `TYPE_NAME`
    /// constant that fails it is a bug in this crate, not bad input.
    ///
    /// `pub(crate)` (not private) so [`crate::__private::conversion`] — a
    /// different module, generated by the [`conversions`] macro — can build
    /// the [`TypeName`]s a [`Conversion`] row carries from `A::TYPE_NAME`
    /// and `B::TYPE_NAME`, the same already-valid contract this function
    /// serves for [`domain_types`].
    pub(crate) fn from_static(name: &'static str) -> Self {
        debug_assert!(
            TYPE_NAME_REGEX.is_match(name),
            "TYPE_NAME {name:?} does not match `{TYPE_NAME_PATTERN}`"
        );
        Self(name.to_string())
    }
}

impl fmt::Display for TypeName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl serde::Serialize for TypeName {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.collect_str(self)
    }
}

impl<'de> serde::Deserialize<'de> for TypeName {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let raw = String::deserialize(deserializer)?;
        Self::parse(&raw).map_err(serde::de::Error::custom)
    }
}

impl schemars::JsonSchema for TypeName {
    fn schema_name() -> Cow<'static, str> {
        Cow::Borrowed("TypeName")
    }

    fn json_schema(_generator: &mut schemars::SchemaGenerator) -> schemars::Schema {
        schemars::json_schema!({
            "type": "string",
            "pattern": TYPE_NAME_PATTERN,
        })
    }
}

/// The published schema pattern for [`TypeRef`]: a bare [`TypeName`], or
/// `list<TypeName>`.
const TYPE_REF_PATTERN: &str = "^(?:[A-Z][A-Za-z0-9]*|list<[A-Z][A-Za-z0-9]*>)$";

/// A reference to a domain type, with an optional `list<...>` cardinality
/// flag. `list<T>` is a cardinality flag on the port or input, not a
/// separate domain type: a list is secret iff its element type is secret.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeRef {
    /// The referenced type's name.
    pub name: TypeName,
    /// Whether this reference names a list of the type, rather than a
    /// single scalar value.
    pub list: bool,
}

impl TypeRef {
    /// A scalar reference to `name`.
    #[must_use]
    pub fn scalar(name: TypeName) -> Self {
        Self { name, list: false }
    }

    /// A `list<name>` reference.
    #[must_use]
    pub fn list_of(name: TypeName) -> Self {
        Self { name, list: true }
    }

    /// The scalar reference to this reference's element type: itself, if
    /// already scalar, or its element type with `list` cleared.
    #[must_use]
    pub fn element(&self) -> Self {
        Self {
            name: self.name.clone(),
            list: false,
        }
    }

    /// Parse `"T"` or `"list<T>"`.
    ///
    /// Rejects any whitespace, `"List<T>"` (the `list` keyword is
    /// case-sensitive), `"list<list<T>>"` (no nested lists), and
    /// `"list<>"` (no empty element name).
    ///
    /// # Errors
    ///
    /// Returns [`ParseError`] when `input` is neither form.
    pub fn parse(input: &str) -> Result<Self, ParseError> {
        if input.chars().any(char::is_whitespace) {
            return Err(ParseError::new(
                "TypeRef",
                format!("{} must not contain whitespace", crate::quoted(input)),
            ));
        }
        if let Some(inner) = input
            .strip_prefix("list<")
            .and_then(|s| s.strip_suffix('>'))
        {
            let name = TypeName::parse(inner).map_err(|err| {
                ParseError::new("TypeRef", format!("list element: {}", err.reason))
            })?;
            return Ok(Self { name, list: true });
        }
        let name = TypeName::parse(input)?;
        Ok(Self { name, list: false })
    }
}

impl fmt::Display for TypeRef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.list {
            write!(f, "list<{}>", self.name)
        } else {
            write!(f, "{}", self.name)
        }
    }
}

impl serde::Serialize for TypeRef {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.collect_str(self)
    }
}

impl<'de> serde::Deserialize<'de> for TypeRef {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let raw = String::deserialize(deserializer)?;
        Self::parse(&raw).map_err(serde::de::Error::custom)
    }
}

impl schemars::JsonSchema for TypeRef {
    fn schema_name() -> Cow<'static, str> {
        Cow::Borrowed("TypeRef")
    }

    fn json_schema(_generator: &mut schemars::SchemaGenerator) -> schemars::Schema {
        schemars::json_schema!({
            "type": "string",
            "pattern": TYPE_REF_PATTERN,
        })
    }
}

/// The reason a [`TypeRegistry`] gives for refusing to parse a secret type
/// from a string. Fake-state seeding constructs secret values through serde
/// `Deserialize` on the concrete type instead.
const SECRET_LITERAL_REFUSAL: &str = "secret types cannot be supplied as literals or inputs";

/// One entry in a [`TypeRegistry`]: a type's catalog description plus its
/// string parser, type-erased to [`DomainObject`].
pub struct TypeEntry {
    /// The type's catalog description.
    pub info: TypeInfo,
    /// Parse a string as this type, type-erased. For a secret type this
    /// always returns `Err` with [`SECRET_LITERAL_REFUSAL`], without ever
    /// calling the type's own parser.
    pub parse: fn(&str) -> Result<Arc<dyn DomainObject>, ParseError>,
    /// Whether an object is actually a value of this entry's own Rust type
    /// `T`, tested by `TypeId` (`Any::is::<T>()`, through
    /// [`crate::object::downcast`]), monomorphized once per type at
    /// registration. Never compares [`DomainType::TYPE_NAME`] strings: a
    /// type name does not pin down a Rust type, since any crate can derive
    /// a type sharing another's name (the exact hole the independent
    /// review of milestone 3d found in a converter's own downcast; see
    /// `docs/research/2026-09-23-m3d-adversarial-pass.md`). `plan` uses
    /// this, through [`TypeRegistry::type_matches`], to parse every
    /// caller-supplied workflow input against its declared type before any
    /// node is planned.
    pub matches: fn(&dyn DomainObject) -> bool,
}

impl TypeEntry {
    /// Build the entry for `T`.
    #[must_use]
    pub fn of<T: DomainType + DomainObject + 'static>() -> Self {
        Self {
            info: TypeInfo::of::<T>(),
            parse: parse_entry::<T>,
            matches: matches_entry::<T>,
        }
    }
}

/// A registered total conversion from one domain type to another: the row
/// [`conversions`] builds, holding the type-erased converter alongside the
/// two names.
///
/// Only ever constructed by [`crate::__private::conversion`], which is to
/// say only by the [`conversions`] macro's own expansion — `Conversion::new`
/// is `pub(crate)`, so outside this crate the only way to hold one is
/// through a row the macro built, which is bounded `B: From<A>` and asserts
/// `!A::IS_SECRET || B::IS_SECRET` at compile time. There is no way to
/// forge a [`Conversion`] whose converter disagrees with a real `From` impl
/// or whose target is less secret than its source.
#[derive(Clone)]
pub struct Conversion {
    from: TypeName,
    to: TypeName,
    convert: fn(&dyn DomainObject) -> Option<Arc<dyn DomainObject>>,
}

impl Conversion {
    /// Build a row. `pub(crate)`: the only caller is
    /// [`crate::__private::conversion`].
    pub(crate) fn new(
        from: TypeName,
        to: TypeName,
        convert: fn(&dyn DomainObject) -> Option<Arc<dyn DomainObject>>,
    ) -> Self {
        Self { from, to, convert }
    }

    /// The source type this row converts from.
    #[must_use]
    pub fn from(&self) -> &TypeName {
        &self.from
    }

    /// The target type this row converts to.
    #[must_use]
    pub fn to(&self) -> &TypeName {
        &self.to
    }

    /// Apply this row's converter to `source`: the converted object when
    /// `source` is an object of the `from` type, else `None`. The test is
    /// the converter's own downcast, by `TypeId`, never the object's type
    /// name, which another Rust type can share. Never panics.
    #[must_use]
    pub fn apply(&self, source: &dyn DomainObject) -> Option<Arc<dyn DomainObject>> {
        (self.convert)(source)
    }
}

impl fmt::Debug for Conversion {
    /// `Conversion(A -> B)`. Never prints the converter function pointer,
    /// which is not meaningful to compare or display.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Conversion({} -> {})", self.from, self.to)
    }
}

impl PartialEq for Conversion {
    /// Equal when `from` and `to` match. Never compares `convert`: two
    /// function pointers to the same monomorphization can still differ by
    /// address across a dylib boundary, and there is exactly one row per
    /// `(from, to)` pair in any one registry (`TypeRegistry::new` asserts
    /// it), so `(from, to)` equality already means "the same row".
    fn eq(&self, other: &Self) -> bool {
        self.from == other.from && self.to == other.to
    }
}

impl Eq for Conversion {}

/// The type-erased parser behind every [`TypeEntry`]. Checks
/// [`DomainType::IS_SECRET`] before calling `T::parse`, so a secret type's
/// input is never validated or echoed.
fn parse_entry<T: DomainType + DomainObject + 'static>(
    input: &str,
) -> Result<Arc<dyn DomainObject>, ParseError> {
    if T::IS_SECRET {
        return Err(ParseError::new(T::TYPE_NAME, SECRET_LITERAL_REFUSAL));
    }
    T::parse(input).map(|value| Arc::new(value) as Arc<dyn DomainObject>)
}

/// The type-erased identity predicate behind every [`TypeEntry`]. `T` is
/// monomorphized once, at registration, so the test itself is `T`'s own
/// `TypeId`, through [`crate::object::downcast`] — never a comparison of
/// `object.type_name()` against `T::TYPE_NAME`, which two different Rust
/// types can share.
fn matches_entry<T: DomainType + 'static>(object: &dyn DomainObject) -> bool {
    crate::object::downcast::<T>(object).is_some()
}

/// The runtime catalog of every domain type this crate defines, keyed by
/// [`TypeName`]. Built once by [`domain_types`] from the same list that
/// builds [`crate::type_infos`].
pub struct TypeRegistry {
    entries: Vec<TypeEntry>,
    index: HashMap<TypeName, usize>,
    conversions: Vec<Conversion>,
    conversion_index: HashMap<(TypeName, TypeName), usize>,
}

impl TypeRegistry {
    /// Build a registry from its entries and its registered conversions,
    /// indexing both.
    ///
    /// # Panics
    ///
    /// Panics (via `debug_assert`) in debug builds if two entries share a
    /// name, if two conversion rows share a `(from, to)` pair, if a row's
    /// `from` equals its `to` (an identity conversion compiles — `From<T>
    /// for T` is a blanket impl — but registering one means nothing and is
    /// certainly a mistake), or if a row names an unregistered type at
    /// either end. The macro that calls this (`domain_types!`, via
    /// `conversion_rows()`) is the one production caller, and any of these
    /// would be a bug in this crate, not bad input; the registry's own test
    /// module additionally asserts all four unconditionally, in every
    /// build profile, over the production registry.
    #[must_use]
    pub fn new(entries: Vec<TypeEntry>, conversions: Vec<Conversion>) -> Self {
        let mut index = HashMap::with_capacity(entries.len());
        for (position, entry) in entries.iter().enumerate() {
            let name = TypeName::from_static(entry.info.name);
            let previous = index.insert(name, position);
            debug_assert!(
                previous.is_none(),
                "duplicate type name in registry: {}",
                entry.info.name
            );
        }

        let mut conversion_index = HashMap::with_capacity(conversions.len());
        for (position, row) in conversions.iter().enumerate() {
            debug_assert!(
                row.from != row.to,
                "identity conversion registered: {} -> {}",
                row.from,
                row.to
            );
            debug_assert!(
                index.contains_key(&row.from),
                "conversion row names an unregistered source type: {}",
                row.from
            );
            debug_assert!(
                index.contains_key(&row.to),
                "conversion row names an unregistered target type: {}",
                row.to
            );
            let previous = conversion_index.insert((row.from.clone(), row.to.clone()), position);
            debug_assert!(
                previous.is_none(),
                "duplicate conversion row: {} -> {}",
                row.from,
                row.to
            );
        }

        Self {
            entries,
            index,
            conversions,
            conversion_index,
        }
    }

    /// Look up the entry for `name`.
    #[must_use]
    pub fn get(&self, name: &TypeName) -> Option<&TypeEntry> {
        self.index
            .get(name)
            .map(|&position| &self.entries[position])
    }

    /// Resolve the entry for `name` for use as a literal: an unregistered
    /// name and a secret type are both refused here, before any input is
    /// looked at.
    ///
    /// Callers that parse a whole list of literals resolve the element type
    /// through this once, so that a list with *no* elements is refused on
    /// exactly the same grounds as a list with one — the map-over-inputs
    /// shape would otherwise silently accept an empty secret-typed or
    /// unregistered list.
    ///
    /// # Errors
    ///
    /// Returns [`ParseError`] when `name` is not registered, or when it
    /// names a secret type.
    pub fn literal_entry(&self, name: &TypeName) -> Result<&TypeEntry, ParseError> {
        let entry = self
            .get(name)
            .ok_or_else(|| ParseError::new("TypeRegistry", format!("unknown type `{name}`")))?;
        if entry.info.secret {
            return Err(ParseError::new(entry.info.name, SECRET_LITERAL_REFUSAL));
        }
        Ok(entry)
    }

    /// Parse `input` as `name`.
    ///
    /// An unknown type name is a [`ParseError`] naming the type. A secret
    /// type refuses with [`SECRET_LITERAL_REFUSAL`] without calling its own
    /// parser.
    ///
    /// # Errors
    ///
    /// Returns [`ParseError`] when `name` is not registered, or when the
    /// registered type refuses or fails to parse `input`.
    pub fn parse(&self, name: &TypeName, input: &str) -> Result<Arc<dyn DomainObject>, ParseError> {
        (self.literal_entry(name)?.parse)(input)
    }

    /// Whether `name` is a secret type, or `None` if `name` is not
    /// registered.
    #[must_use]
    pub fn is_secret(&self, name: &TypeName) -> Option<bool> {
        self.get(name).map(|entry| entry.info.secret)
    }

    /// Whether `object` is actually a value of the Rust type registered as
    /// `name`, tested by that entry's own [`TypeEntry::matches`] (`TypeId`,
    /// via `Any::is`), never by comparing [`DomainType::TYPE_NAME`]
    /// strings — a type name does not pin down a Rust type: two different
    /// crates can each derive a type sharing one (the independent review
    /// of milestone 3d, `docs/research/2026-09-23-m3d-adversarial-pass.md`).
    /// `None` when `name` is not registered.
    #[must_use]
    pub fn type_matches(&self, name: &TypeName, object: &dyn DomainObject) -> Option<bool> {
        self.get(name).map(|entry| (entry.matches)(object))
    }

    /// Iterate every registered entry.
    pub fn iter(&self) -> impl Iterator<Item = &TypeEntry> {
        self.entries.iter()
    }

    /// The one registered conversion from `from` to `to`, if any: a single
    /// `HashMap::get` on the owned pair, and nothing more. There is no
    /// transitive search — if `A` converts to `B` and `B` converts to `C`,
    /// this returns `None` for `probe_conversion(A, C)`, exactly as if no
    /// row existed at all. `willikins-core`'s `check` is this crate's only
    /// sanctioned caller (`clippy.toml`); `plan` and `apply` never call it,
    /// reading the conversion `check` already chose from `Checked` instead.
    #[must_use]
    pub fn probe_conversion(&self, from: &TypeName, to: &TypeName) -> Option<Conversion> {
        let key = (from.clone(), to.clone());
        self.conversion_index
            .get(&key)
            .map(|&position| self.conversions[position].clone())
    }

    /// Every registered conversion's `(from, to)` pair, in declaration
    /// order, names only. Never a [`Conversion`] itself — the catalogue and
    /// any other outside reader can see which pairs exist without ever
    /// holding a converter.
    pub fn conversion_pairs(&self) -> impl Iterator<Item = (&TypeName, &TypeName)> {
        self.conversions.iter().map(|row| (&row.from, &row.to))
    }
}

/// Generate `type_infos()`, `registry()`, and `assert_all_examples_parse()`
/// from one list of domain types, so the type catalog and the type registry
/// cannot drift apart.
///
/// Invoked exactly once, in `lib.rs`, listing every domain type this crate
/// defines.
macro_rules! domain_types {
    ($($ty:ty),+ $(,)?) => {
        /// The beginning of the type catalog: every domain type this crate
        /// defines. Later milestone-1 tasks append the org,
        /// resource-identity, and credential types.
        #[must_use]
        pub fn type_infos() -> ::std::vec::Vec<$crate::TypeInfo> {
            ::std::vec![$($crate::TypeInfo::of::<$ty>()),+]
        }

        /// The type registry: every domain type in [`type_infos`], keyed by
        /// name, with its string parser, plus every registered conversion
        /// (this crate's own private `conversion_rows`, in `lib.rs`).
        #[must_use]
        pub fn registry() -> &'static $crate::registry::TypeRegistry {
            static REGISTRY: ::std::sync::LazyLock<$crate::registry::TypeRegistry> =
                ::std::sync::LazyLock::new(|| {
                    $crate::registry::TypeRegistry::new(
                        ::std::vec![
                            $($crate::registry::TypeEntry::of::<$ty>()),+
                        ],
                        $crate::conversion_rows(),
                    )
                });
            &REGISTRY
        }

        /// Assert every listed type's own example parses through its own
        /// [`crate::DomainType::parse`] — bypassing the registry, which
        /// refuses to parse a secret type from a string at all, so this is
        /// the only way to check a secret type's example.
        pub fn assert_all_examples_parse() {
            $($crate::assert_example_parses::<$ty>();)+
        }
    };
}

pub(crate) use domain_types;

/// Build a list of registered conversions, one row per `A => B` pair.
///
/// `conversions![A => B, C => D]` is an **expression** of type
/// `Vec<Conversion>`; an empty list (`conversions![]`) is allowed, and a
/// trailing comma is optional. Used three ways: `willikins-types`'s own
/// `lib.rs` lists the one production row inside `conversion_rows`; a test
/// (in this crate or in `willikins-core`) builds a synthetic table over
/// local types; and the two trybuild fixtures under `tests/conversions/`
/// prove what each expansion step guarantees on its own.
///
/// Each `A => B` expands to three things, all load-bearing:
///
/// 1. A `const _: () = assert!(...)` that fails to compile — E0080 at
///    evaluation, not merely a runtime panic — when `A::IS_SECRET` is true
///    and `B::IS_SECRET` is false. "Secrecy only goes up." This is the one
///    macro-exported name to which `TypeName`'s `from_static`-style
///    already-valid contract does not apply: nothing here trusts `A` or
///    `B`, the assertion is over their own declared `IS_SECRET` consts.
/// 2. A call to [`crate::__private::conversion::<A, B>()`], bounded
///    `B: From<A>` — so a row with no hand-written `From` impl is a plain
///    E0277, and the row can never drift from the impl it names. That
///    function's own `const { }` block is a second, weaker belt on the
///    same secrecy rule; see its doc for why this macro's own `const _`
///    above is the real guarantee.
/// 3. The row itself, carrying the type-erased converter, is what the
///    whole expression evaluates to — nothing here is *only* a
///    compile-time check with no runtime value, so a workspace build's
///    ordinary `cargo test` cannot skip step 1's evaluation the way a
///    monomorphization-gated check could.
///
/// "One hop, no chains": this macro has no idea what other rows exist. A
/// document that binds an `A` where a `C` is wanted, with only `A => B`
/// and `B => C` registered, is refused exactly as if neither row existed —
/// see `willikins-core`'s own no-chains test.
#[macro_export]
macro_rules! conversions {
    ( $( $from:ty => $to:ty ),* $(,)? ) => {
        ::std::vec![
            $(
                {
                    const _: () = ::std::assert!(
                        !<$from as $crate::DomainType>::IS_SECRET
                            || <$to as $crate::DomainType>::IS_SECRET,
                        "conversions!: a conversion may not make a value less secret; \
                         its target must be at least as secret as its source"
                    );
                    #[allow(clippy::disallowed_methods)] // the macro is the one sanctioned caller
                    let row = $crate::__private::conversion::<$from, $to>();
                    row
                }
            ),*
        ]
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{DopplerSecretValue, DopplerServiceToken, GitHubOrg};

    // -------------------------------------------------------------
    // TypeName
    // -------------------------------------------------------------

    #[test]
    fn type_name_accepts_pascal_case() {
        assert_eq!(
            TypeName::parse("GitHubRepo").unwrap().as_str(),
            "GitHubRepo"
        );
    }

    #[test]
    fn type_name_accepts_a_single_letter() {
        assert!(TypeName::parse("T").is_ok());
    }

    #[test]
    fn type_name_rejects_lowercase_start() {
        assert!(TypeName::parse("gitHubRepo").is_err());
    }

    #[test]
    fn type_name_rejects_empty() {
        assert!(TypeName::parse("").is_err());
    }

    #[test]
    fn type_name_rejects_separators() {
        assert!(TypeName::parse("GitHub-Repo").is_err());
        assert!(TypeName::parse("GitHub_Repo").is_err());
        assert!(TypeName::parse("GitHub Repo").is_err());
    }

    #[test]
    fn type_name_displays_as_its_string() {
        assert_eq!(
            TypeName::parse("GitHubRepo").unwrap().to_string(),
            "GitHubRepo"
        );
    }

    #[test]
    fn type_name_serde_round_trips() {
        let name = TypeName::parse("GitHubRepo").unwrap();
        let json = serde_json::to_string(&name).unwrap();
        assert_eq!(json, "\"GitHubRepo\"");
        assert_eq!(serde_json::from_str::<TypeName>(&json).unwrap(), name);
    }

    #[test]
    fn type_name_deserialize_rejects_invalid() {
        assert!(serde_json::from_str::<TypeName>("\"not valid\"").is_err());
    }

    #[test]
    fn type_name_orders_lexicographically() {
        let a = TypeName::parse("Alpha").unwrap();
        let b = TypeName::parse("Beta").unwrap();
        assert!(a < b);
    }

    #[test]
    fn type_name_schema_is_a_pattern_string() {
        let schema = serde_json::to_value(schemars::schema_for!(TypeName)).unwrap();
        assert_eq!(schema["type"], "string");
        assert_eq!(schema["pattern"], TYPE_NAME_PATTERN);
    }

    // -------------------------------------------------------------
    // TypeRef
    // -------------------------------------------------------------

    #[test]
    fn type_ref_parses_a_scalar() {
        let ty_ref = TypeRef::parse("GitHubRepo").unwrap();
        assert_eq!(ty_ref.name.as_str(), "GitHubRepo");
        assert!(!ty_ref.list);
    }

    #[test]
    fn type_ref_parses_a_list() {
        let ty_ref = TypeRef::parse("list<GitHubRepo>").unwrap();
        assert_eq!(ty_ref.name.as_str(), "GitHubRepo");
        assert!(ty_ref.list);
    }

    #[test]
    fn type_ref_rejects_capitalized_list_keyword() {
        assert!(TypeRef::parse("List<GitHubRepo>").is_err());
    }

    #[test]
    fn type_ref_rejects_nested_lists() {
        assert!(TypeRef::parse("list<list<GitHubRepo>>").is_err());
    }

    #[test]
    fn type_ref_rejects_an_empty_list_element() {
        assert!(TypeRef::parse("list<>").is_err());
    }

    #[test]
    fn type_ref_rejects_whitespace_variants() {
        assert!(TypeRef::parse(" GitHubRepo").is_err());
        assert!(TypeRef::parse("GitHubRepo ").is_err());
        assert!(TypeRef::parse("list< GitHubRepo>").is_err());
        assert!(TypeRef::parse("list<GitHubRepo >").is_err());
        assert!(TypeRef::parse("list <GitHubRepo>").is_err());
    }

    #[test]
    fn type_ref_accepts_the_no_whitespace_variant() {
        assert!(TypeRef::parse("list<GitHubRepo>").is_ok());
    }

    #[test]
    fn type_ref_displays_a_scalar_and_a_list() {
        assert_eq!(
            TypeRef::parse("GitHubRepo").unwrap().to_string(),
            "GitHubRepo"
        );
        assert_eq!(
            TypeRef::parse("list<GitHubRepo>").unwrap().to_string(),
            "list<GitHubRepo>"
        );
    }

    #[test]
    fn type_ref_serde_round_trips() {
        for text in ["GitHubRepo", "list<GitHubRepo>"] {
            let ty_ref = TypeRef::parse(text).unwrap();
            let json = serde_json::to_string(&ty_ref).unwrap();
            assert_eq!(json, format!("{text:?}"));
            assert_eq!(serde_json::from_str::<TypeRef>(&json).unwrap(), ty_ref);
        }
    }

    #[test]
    fn type_ref_schema_is_a_pattern_string() {
        let schema = serde_json::to_value(schemars::schema_for!(TypeRef)).unwrap();
        assert_eq!(schema["type"], "string");
        assert_eq!(schema["pattern"], TYPE_REF_PATTERN);
    }

    #[test]
    fn type_ref_scalar_and_list_of_constructors() {
        let name = TypeName::parse("GitHubRepo").unwrap();
        assert_eq!(
            TypeRef::scalar(name.clone()),
            TypeRef::parse("GitHubRepo").unwrap()
        );
        assert_eq!(
            TypeRef::list_of(name),
            TypeRef::parse("list<GitHubRepo>").unwrap()
        );
    }

    #[test]
    fn type_ref_element_strips_the_list_flag() {
        let list_ref = TypeRef::parse("list<GitHubRepo>").unwrap();
        let element = list_ref.element();
        assert_eq!(element.name, list_ref.name);
        assert!(!element.list);
    }

    // -------------------------------------------------------------
    // TypeRegistry
    // -------------------------------------------------------------

    #[test]
    fn registry_gets_a_registered_non_secret_type() {
        let name = TypeName::parse("GitHubOrg").unwrap();
        let entry = crate::registry()
            .get(&name)
            .expect("GitHubOrg is registered");
        assert_eq!(entry.info.name, "GitHubOrg");
        assert!(!entry.info.secret);
    }

    #[test]
    fn registry_get_returns_none_for_an_unknown_type() {
        let name = TypeName::parse("NoSuchType").unwrap();
        assert!(crate::registry().get(&name).is_none());
    }

    #[test]
    fn registry_parses_a_non_secret_type() {
        let name = TypeName::parse("GitHubOrg").unwrap();
        let value = crate::registry().parse(&name, "lightless-labs").unwrap();
        assert_eq!(value.type_name(), "GitHubOrg");
        let org = crate::downcast::<GitHubOrg>(&*value).expect("downcasts to GitHubOrg");
        assert_eq!(org.as_str(), "lightless-labs");
    }

    #[test]
    fn registry_parse_of_unknown_type_names_the_type() {
        let name = TypeName::parse("NoSuchType").unwrap();
        let err = crate::registry().parse(&name, "anything").unwrap_err();
        assert!(
            err.reason.contains("NoSuchType"),
            "reason was {:?}",
            err.reason
        );
    }

    #[test]
    fn registry_is_secret_reports_secrecy_for_registered_types() {
        let secret = TypeName::parse("DopplerServiceToken").unwrap();
        let plain = TypeName::parse("GitHubOrg").unwrap();
        let unknown = TypeName::parse("NoSuchType").unwrap();
        assert_eq!(crate::registry().is_secret(&secret), Some(true));
        assert_eq!(crate::registry().is_secret(&plain), Some(false));
        assert_eq!(crate::registry().is_secret(&unknown), None);
    }

    #[test]
    fn registry_iter_covers_every_registered_type() {
        let names: std::collections::HashSet<&str> = crate::registry()
            .iter()
            .map(|entry| entry.info.name)
            .collect();
        assert!(names.contains("GitHubOrg"));
        assert!(names.contains("DopplerServiceToken"));
        assert_eq!(names.len(), crate::type_infos().len());
    }

    // -------------------------------------------------------------
    // Secret refusal
    // -------------------------------------------------------------

    #[test]
    fn registry_refuses_to_parse_doppler_service_token_as_a_literal() {
        let name = TypeName::parse("DopplerServiceToken").unwrap();
        // `concat!`-split: a value shaped like a real token, on purpose,
        // but not spelled contiguously in this file.
        let err = crate::registry()
            .parse(
                &name,
                concat!("dp.st.prd.", "exampleexampleexampleexampleexampleexample"),
            )
            .unwrap_err();
        assert_eq!(err.reason, SECRET_LITERAL_REFUSAL);
    }

    #[test]
    fn registry_refuses_to_parse_doppler_secret_value_as_a_literal() {
        let name = TypeName::parse("DopplerSecretValue").unwrap();
        let err = crate::registry().parse(&name, "s3cr3t-value").unwrap_err();
        assert_eq!(err.reason, SECRET_LITERAL_REFUSAL);
    }

    #[test]
    fn registry_secret_refusal_never_touches_the_input_even_when_invalid() {
        // An input that would fail DopplerServiceToken's own pattern check
        // (too short) still gets the generic refusal, not a pattern error,
        // proving the type's own parser is never called.
        let name = TypeName::parse("DopplerServiceToken").unwrap();
        let err = crate::registry()
            .parse(&name, "MARKER-too-short")
            .unwrap_err();
        assert_eq!(err.reason, SECRET_LITERAL_REFUSAL);
        assert!(!err.reason.contains("MARKER"));
    }

    #[test]
    fn literal_entry_resolves_a_non_secret_type() {
        let name = TypeName::parse("GitHubOrg").unwrap();
        let Ok(entry) = crate::registry().literal_entry(&name) else {
            panic!("GitHubOrg is registered and not secret")
        };
        assert_eq!(entry.info.name, "GitHubOrg");
    }

    #[test]
    fn literal_entry_refuses_a_secret_type_with_no_input_at_all() {
        // The refusal must not depend on there being an input to reject:
        // this is what stops an empty `list<Secret>` literal.
        let name = TypeName::parse("DopplerServiceToken").unwrap();
        let Err(err) = crate::registry().literal_entry(&name) else {
            panic!("a secret type must be refused")
        };
        assert_eq!(err.reason, SECRET_LITERAL_REFUSAL);
        assert_eq!(err.type_name, "DopplerServiceToken");
    }

    #[test]
    fn literal_entry_refuses_an_unregistered_type() {
        let name = TypeName::parse("NoSuchType").unwrap();
        let Err(err) = crate::registry().literal_entry(&name) else {
            panic!("an unregistered type must be refused")
        };
        assert!(err.reason.contains("NoSuchType"), "{}", err.reason);
    }

    #[test]
    fn secret_type_deserialize_is_unchanged_by_the_registry_refusal() {
        // The registry refuses secret literals, but plain serde
        // `Deserialize` on the concrete type still works: this is how
        // fake-state seeding constructs secret values.
        let token: DopplerServiceToken = serde_json::from_str(concat!(
            "\"dp.st.prd.",
            "exampleexampleexampleexampleexampleexample\""
        ))
        .unwrap();
        assert_eq!(format!("{token:?}"), "[REDACTED DopplerServiceToken]");

        let value: DopplerSecretValue = serde_json::from_str("\"s3cr3t-value\"").unwrap();
        assert_eq!(format!("{value:?}"), "[REDACTED DopplerSecretValue]");
    }

    // -------------------------------------------------------------
    // Conversion / probe_conversion / conversion_pairs (milestone 3d)
    // -------------------------------------------------------------

    #[derive(DomainType)]
    #[domain(
        pattern = "[a-z]+",
        description = "A registry test type (conversion source).",
        example = "a"
    )]
    struct RegistryTestA(String);

    #[derive(DomainType)]
    #[domain(
        pattern = "[a-z]+",
        description = "A registry test type (conversion target).",
        example = "b"
    )]
    struct RegistryTestB(String);

    impl From<RegistryTestA> for RegistryTestB {
        fn from(a: RegistryTestA) -> Self {
            Self::parse(a.as_str())
                .unwrap_or_else(|err| unreachable!("RegistryTestA's own string: {err}"))
        }
    }

    fn synthetic_registry_with_one_row() -> TypeRegistry {
        TypeRegistry::new(
            ::std::vec![
                TypeEntry::of::<RegistryTestA>(),
                TypeEntry::of::<RegistryTestB>(),
            ],
            crate::conversions![RegistryTestA => RegistryTestB],
        )
    }

    #[test]
    #[allow(clippy::disallowed_methods)] // a unit test of the probe itself; in production only `check` may call it
    fn probe_conversion_finds_the_one_registered_row() {
        let registry = synthetic_registry_with_one_row();
        let a = TypeName::parse("RegistryTestA").unwrap();
        let b = TypeName::parse("RegistryTestB").unwrap();
        let row = registry
            .probe_conversion(&a, &b)
            .expect("RegistryTestA -> RegistryTestB is registered");
        assert_eq!(row.from(), &a);
        assert_eq!(row.to(), &b);
    }

    #[test]
    #[allow(clippy::disallowed_methods)] // a unit test of the probe itself; in production only `check` may call it
    fn probe_conversion_returns_none_for_the_reverse_pair() {
        let registry = synthetic_registry_with_one_row();
        let a = TypeName::parse("RegistryTestA").unwrap();
        let b = TypeName::parse("RegistryTestB").unwrap();
        // The reverse direction was never registered: no row, no chain,
        // no implicit symmetry.
        assert!(registry.probe_conversion(&b, &a).is_none());
    }

    #[test]
    #[allow(clippy::disallowed_methods)] // a unit test of the probe itself; in production only `check` may call it
    fn probe_conversion_returns_none_for_an_unrelated_pair() {
        let registry = synthetic_registry_with_one_row();
        let a = TypeName::parse("RegistryTestA").unwrap();
        assert!(registry.probe_conversion(&a, &a).is_none());
    }

    #[test]
    fn conversion_pairs_lists_names_only_in_declaration_order() {
        let registry = synthetic_registry_with_one_row();
        let pairs: Vec<(&str, &str)> = registry
            .conversion_pairs()
            .map(|(from, to)| (from.as_str(), to.as_str()))
            .collect();
        assert_eq!(pairs, vec![("RegistryTestA", "RegistryTestB")]);
    }

    // -------------------------------------------------------------
    // TypeRegistry::type_matches (follow-up to milestone 3d, 2026-09-24:
    // "I'd much rather have it fail loudly at parsing than silently go
    // through" -- the per-type identity predicate `plan`'s own
    // input-parsing check is built on)
    // -------------------------------------------------------------

    /// Another Rust type whose `TYPE_NAME` is also `RegistryTestA`.
    /// `TYPE_NAME` is `stringify!` of the struct's own name, so any crate
    /// can declare one; `type_matches` must tell it apart from the real
    /// `RegistryTestA` by `TypeId`, never by comparing that shared name.
    mod impostor {
        use super::DomainType;

        #[derive(DomainType)]
        #[domain(
            pattern = "[a-z]+",
            description = "Not the real RegistryTestA.",
            example = "a"
        )]
        pub(super) struct RegistryTestA(String);
    }

    #[test]
    fn type_matches_is_true_for_a_real_value_of_the_registered_type() {
        let registry = synthetic_registry_with_one_row();
        let name = TypeName::parse("RegistryTestA").unwrap();
        let value = RegistryTestA::parse("a").unwrap();
        assert_eq!(registry.type_matches(&name, &value), Some(true));
    }

    #[test]
    fn type_matches_is_false_for_a_same_named_value_of_another_rust_type() {
        let registry = synthetic_registry_with_one_row();
        let name = TypeName::parse("RegistryTestA").unwrap();
        let impostor = impostor::RegistryTestA::parse("a").unwrap();
        assert_eq!(impostor.type_name(), "RegistryTestA");
        assert_eq!(registry.type_matches(&name, &impostor), Some(false));
    }

    #[test]
    fn type_matches_is_false_for_a_value_of_a_different_registered_type() {
        let registry = synthetic_registry_with_one_row();
        let name = TypeName::parse("RegistryTestA").unwrap();
        let other = RegistryTestB::parse("b").unwrap();
        assert_eq!(registry.type_matches(&name, &other), Some(false));
    }

    #[test]
    fn type_matches_is_none_for_an_unregistered_name() {
        let registry = synthetic_registry_with_one_row();
        let name = TypeName::parse("NeverRegistered").unwrap();
        let value = RegistryTestA::parse("a").unwrap();
        assert_eq!(registry.type_matches(&name, &value), None);
    }

    #[test]
    #[should_panic(expected = "duplicate conversion row")]
    fn new_refuses_a_duplicate_conversion_row() {
        let _ = TypeRegistry::new(
            ::std::vec![
                TypeEntry::of::<RegistryTestA>(),
                TypeEntry::of::<RegistryTestB>(),
            ],
            crate::conversions![RegistryTestA => RegistryTestB, RegistryTestA => RegistryTestB],
        );
    }

    #[test]
    #[should_panic(expected = "identity conversion registered")]
    fn new_refuses_an_identity_conversion_row() {
        let _ = TypeRegistry::new(
            ::std::vec![TypeEntry::of::<RegistryTestA>()],
            crate::conversions![RegistryTestA => RegistryTestA],
        );
    }

    #[test]
    #[should_panic(expected = "unregistered")]
    fn new_refuses_a_row_naming_an_unregistered_type() {
        // RegistryTestB is never added to `entries`, only RegistryTestA is.
        let _ = TypeRegistry::new(
            ::std::vec![TypeEntry::of::<RegistryTestA>()],
            crate::conversions![RegistryTestA => RegistryTestB],
        );
    }

    /// The same three invariants `TypeRegistry::new`'s `debug_assert`s
    /// check, asserted unconditionally over the *production* registry, in
    /// every build profile -- not only debug.
    /// Milestone 3d's verifier: "secrecy only goes up" is asserted at
    /// compile time over [`DomainType::IS_SECRET`], and that const
    /// defaults to `false`. A hand-written secret type that forgot to set
    /// it would therefore let a secret-to-public `conversions!` row
    /// compile, and `check`'s secret rule (which reads the same flag
    /// through the registry) would miss it too. This pins, for every
    /// registered type, that a type the registry calls public really is
    /// public by its own [`DomainObject`] -- its example parses, and the
    /// object says `is_secret() == false` and renders in plain -- and that
    /// a type the registry calls secret is refused as a literal.
    #[test]
    fn every_registered_type_is_as_secret_as_its_is_secret_const_says() {
        let registry = crate::registry();
        for entry in registry.iter() {
            let info = &entry.info;
            if info.secret {
                assert!(
                    (entry.parse)(info.example).is_err(),
                    "{}: a secret type must be refused as a literal",
                    info.name
                );
                continue;
            }
            let object = (entry.parse)(info.example)
                .unwrap_or_else(|err| panic!("{}: its own example must parse: {err}", info.name));
            assert!(
                !object.is_secret(),
                "{}: IS_SECRET is false but its DomainObject says it is secret",
                info.name
            );
            assert!(
                matches!(object.render(), crate::object::Rendered::Plain(_)),
                "{}: IS_SECRET is false but it renders redacted",
                info.name
            );
        }
    }

    #[test]
    fn the_production_registry_has_no_duplicate_or_identity_conversion_row() {
        let registry = crate::registry();
        let mut seen = ::std::collections::HashSet::new();
        for (from, to) in registry.conversion_pairs() {
            assert_ne!(from, to, "identity conversion row: {from} -> {to}");
            assert!(
                seen.insert((from.clone(), to.clone())),
                "duplicate conversion row: {from} -> {to}"
            );
            assert!(
                registry.get(from).is_some(),
                "conversion row names an unregistered source type: {from}"
            );
            assert!(
                registry.get(to).is_some(),
                "conversion row names an unregistered target type: {to}"
            );
        }
    }

    /// Milestone 3g decision (e): `Text` is public Doppler-sourced text
    /// (wall two) and must never reach a committed file. The only route
    /// into a [`crate::RepoFile`] is `TemplateValue`, whose grammar refuses
    /// characters `Text` accepts, so a `Text => TemplateValue` row would
    /// let a document convert an ordinary public value into one that could
    /// reach a file. No such row may ever be registered.
    #[test]
    fn the_production_registry_has_no_text_to_template_value_conversion_row() {
        let registry = crate::registry();
        let text = TypeName::parse("Text").unwrap();
        let template_value = TypeName::parse("TemplateValue").unwrap();
        assert!(
            registry
                .conversion_pairs()
                .all(|(from, to)| !(from == &text && to == &template_value)),
            "a Text => TemplateValue conversion row exists; decision (e) forbids it"
        );
    }

    /// Adversarial pass over E2 (milestone 3g decision (e)): a committed
    /// file's bytes are a document-literal `TemplateSource` plus
    /// `TemplateValue` substitutions, and a `RepoFile` is produced only by
    /// `repo.file.render`. So no conversion row may ever *target* either:
    /// `Text => TemplateSource` would even be total (both are bounded at
    /// 65,536 characters) and would turn `doppler.value.get`'s public
    /// `Text` into a template; a row into `RepoFile` would let a value
    /// become a whole file. The row above pins only `Text => TemplateValue`.
    #[test]
    fn the_production_registry_has_no_conversion_row_into_template_source_or_repo_file() {
        let registry = crate::registry();
        let template_source = TypeName::parse("TemplateSource").unwrap();
        let repo_file = TypeName::parse("RepoFile").unwrap();
        let offending: Vec<_> = registry
            .conversion_pairs()
            .filter(|(_, to)| *to == &template_source || *to == &repo_file)
            .collect();
        assert!(
            offending.is_empty(),
            "decision (e) forbids a conversion into TemplateSource or RepoFile: {offending:?}"
        );
    }
}
