[package]
name = "willikins-derive"
description = "#[derive(DomainType)] for willikins domain newtypes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
regex.workspace = true

[lints]
workspace = true
