//! Whole-catalog tests: every domain type this crate defines is registered
//! in the type registry exactly once with a non-empty description, its own
//! example parses (through the registry for non-secret types, and directly
//! through its own `DomainType::parse` for secret types, since the registry
//! refuses to parse a secret type from a string at all), and the catalog's
//! published JSON shape is pinned by an insta snapshot so drift is visible
//! in review.

use std::collections::HashSet;

use willikins_types::*;

#[test]
fn every_domain_type_is_registered_exactly_once_and_its_example_parses() {
    // Secret types' examples can only be checked directly against their own
    // parser: the registry refuses to parse a secret type from a string at
    // all. This call list is generated by the same `domain_types!` macro
    // invocation that builds the registry, so it cannot fall out of sync
    // with which types exist.
    willikins_types::assert_all_examples_parse();

    let entries: Vec<_> = registry().iter().collect();

    let names: Vec<&'static str> = entries.iter().map(|entry| entry.info.name).collect();
    let name_set: HashSet<&str> = names.iter().copied().collect();
    assert_eq!(
        name_set.len(),
        names.len(),
        "the type registry lists the same type name more than once"
    );

    for entry in &entries {
        assert!(
            !entry.info.description.is_empty(),
            "{}: description must not be empty",
            entry.info.name
        );

        if entry.info.secret {
            // Already covered above, directly: the registry itself must
            // refuse to parse it.
            let name = registry::TypeName::parse(entry.info.name).unwrap();
            let err = registry().parse(&name, entry.info.example).unwrap_err();
            assert_eq!(
                err.reason, "secret types cannot be supplied as literals or inputs",
                "{}: registry did not refuse a secret literal",
                entry.info.name
            );
        } else {
            let name = registry::TypeName::parse(entry.info.name).unwrap();
            registry()
                .parse(&name, entry.info.example)
                .unwrap_or_else(|err| {
                    panic!(
                        "{}: example {:?} does not parse through the registry: {err}",
                        entry.info.name, entry.info.example
                    )
                });
        }
    }

    // `type_infos()` and the registry are built from the same macro
    // invocation, so they must always agree on the set of types.
    let catalog_names: HashSet<&str> = type_infos().iter().map(|info| info.name).collect();
    assert_eq!(
        catalog_names, name_set,
        "type_infos() and the type registry disagree on which types exist"
    );
}

#[test]
fn catalog_json_snapshot() {
    let json = serde_json::to_string_pretty(&type_infos()).unwrap();
    insta::assert_snapshot!(json);
}
