//! Whole-catalog tests: every domain type this crate defines is registered
//! in the type registry exactly once with a non-empty description, its own
//! example parses (through the registry for non-secret types, and directly
//! through its own `DomainType::parse` for secret types, since the registry
//! refuses to parse a secret type from a string at all), and the catalog's
//! published JSON shape is pinned by an insta snapshot so drift is visible
//! in review.

use std::collections::HashSet;

use willikins_types::*;

#[test]
fn every_domain_type_is_registered_exactly_once_and_its_example_parses() {
    // Secret types' examples can only be checked directly against their own
    // parser: the registry refuses to parse a secret type from a string at
    // all. This call list is generated by the same `domain_types!` macro
    // invocation that builds the registry, so it cannot fall out of sync
    // with which types exist.
    willikins_types::assert_all_examples_parse();

    let entries: Vec<_> = registry().iter().collect();

    let names: Vec<&'static str> = entries.iter().map(|entry| entry.info.name).collect();
    let name_set: HashSet<&str> = names.iter().copied().collect();
    assert_eq!(
        name_set.len(),
        names.len(),
        "the type registry lists the same type name more than once"
    );

    for entry in &entries {
        assert!(
            !entry.info.description.is_empty(),
            "{}: description must not be empty",
            entry.info.name
        );

        if entry.info.secret {
            // Already covered above, directly: the registry itself must
            // refuse to parse it.
            let name = registry::TypeName::parse(entry.info.name).unwrap();
            let err = registry().parse(&name, entry.info.example).unwrap_err();
            assert_eq!(
                err.reason, "secret types cannot be supplied as literals or inputs",
                "{}: registry did not refuse a secret literal",
                entry.info.name
            );
        } else {
            let name = registry::TypeName::parse(entry.info.name).unwrap();
            registry()
                .parse(&name, entry.info.example)
                .unwrap_or_else(|err| {
                    panic!(
                        "{}: example {:?} does not parse through the registry: {err}",
                        entry.info.name, entry.info.example
                    )
                });
        }
    }

    // `type_infos()` and the registry are built from the same macro
    // invocation, so they must always agree on the set of types.
    let catalog_names: HashSet<&str> = type_infos().iter().map(|info| info.name).collect();
    assert_eq!(
        catalog_names, name_set,
        "type_infos() and the type registry disagree on which types exist"
    );
}

#[test]
fn catalog_json_snapshot() {
    let json = serde_json::to_string_pretty(&type_infos()).unwrap();
    // Every secret type's `example` must itself be a valid, pattern-shaped
    // instance of its own type (`assert_example_parses`, exercised above
    // and by `assert_all_examples_parse`) -- which is exactly the shape a
    // provider's own secret scanner looks for. This snapshot's only job
    // (see the module doc) is to catch structural drift in the published
    // catalog, not to pin those bytes, so each secret type's real example
    // is replaced by a stable placeholder wherever it appears -- both
    // `TypeInfo.example` and the copy repeated inside its JSON schema's
    // own `examples` array -- before the snapshot is taken. The other
    // test in this file still parses the real, unredacted value.
    // Matched against the JSON-*encoded* form of each example, not the
    // raw Rust string: `AppleSigningKey`'s example is the first secret
    // example to carry embedded newlines (a multi-line PEM), and
    // `serde_json::to_string_pretty` escapes those as a literal `\n`
    // two-character sequence in `json` -- a `.replace(info.example, ...)`
    // using the raw (real-newline) string would never match and the PEM
    // would leak into the snapshot unredacted. Re-encoding `info.example`
    // the same way `type_infos()` was serialized, then trimming the
    // surrounding quotes `serde_json::to_string` adds, recovers exactly
    // the substring that appears inside `json`, for any example
    // regardless of which characters it contains.
    let mut redacted = json;
    for info in type_infos().iter().filter(|info| info.secret) {
        let json_encoded = serde_json::to_string(info.example).unwrap();
        let inner = &json_encoded[1..json_encoded.len() - 1];
        redacted = redacted.replace(inner, "[ELIDED SECRET EXAMPLE]");
    }
    insta::assert_snapshot!(redacted);
}
